### PR TITLE
feat: add manual torrent adding

### PR DESCRIPTION
**Pull request by davidemarcoli**
Merge after https://github.com/rivenmedia/riven/pull/785

### CODE REVIEW

**Comment by filiptrplan** [comment]
Not sure if this is ready but it currently does not work. 

I tried to add the movie Inside Out 2 with the hash `8FAE371CB820400ECC974A39912E42CAB138C263` but it throws an error:

```
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "item_id" of relation "MediaItem" violates not-null constraint
DETAIL:  Failing row contains (208, null, null, mediaitem, 2024-10-13 15:01:44.363347, riven, null, null, null, 0, {}, f, null, 0, null, null, null, null, {}, f, null, tt22022452, null, null, null, null, null, null, null, [], null, null, null, null, Unknown).

[SQL: INSERT INTO "MediaItem" (item_id, number, type, requested_at, requested_by, requested_id, indexed_at, scraped_at, scraped_times, active_stream, symlinked, symlinked_at, symlinked_times, symlink_path, file, folder, alternative_folder, aliases, is_anime, title, imdb_id, tvdb_id, tmdb_id, network, country, language, aired_at, year, genres, key, guid, update_folder, overseerr_id, last_state) VALUES (%(item_id)s, %(number)s, %(type)s, %(requested_at)s, %(requested_by)s, %(requested_id)s, %(indexed_at)s, %(scraped_at)s, %(scraped_times)s, %(active_stream)s, %(symlinked)s, %(symlinked_at)s, %(symlinked_times)s, %(symlink_path)s, %(file)s, %(folder)s, %(alternative_folder)s, %(aliases)s, %(is_anime)s, %(title)s, %(imdb_id)s, %(tvdb_id)s, %(tmdb_id)s, %(network)s, %(country)s, %(language)s, %(aired_at)s, %(year)s, %(genres)s, %(key)s, %(guid)s, %(update_folder)s, %(overseerr_id)s, %(last_state)s) RETURNING "MediaItem"._id]
[parameters: {'item_id': None, 'number': None, 'type': 'mediaitem', 'requested_at': datetime.datetime(2024, 10, 13, 15, 1, 44, 363347), 'requested_by': 'riven', 'requested_id': None, 'indexed_at': None, 'scraped_at': None, 'scraped_times': 0, 'active_stream': '{}', 'symlinked': False, 'symlinked_at': None, 'symlinked_times': 0, 'symlink_path': None, 'file': None, 'folder': None, 'alternative_folder': None, 'aliases': '{}', 'is_anime': False, 'title': None, 'imdb_id': 'tt22022452', 'tvdb_id': None, 'tmdb_id': None, 'network': None, 'country': None, 'language': None, 'aired_at': None, 'year': None, 'genres': '[]', 'key': None, 'guid': None, 'update_folder': None, 'overseerr_id': None, 'last_state': 'Unknown'}]
```

**Comment by filiptrplan** [comment]
Also the Request button is still visible after the movie is requested and added. This doesn't happen in `dev` so it should be something in this PR.

**Comment by AyushSehrawat** [comment]
> Also the Request button is still visible after the movie is requested and added. This doesn't happen in `dev` so it should be something in this PR.

Don't think that's the issue. Issue is that when someone requests the media, it's not added instantaneously into db after backend api call (sometimes it's quick sometimes it's slow). So you need to manually reload to see it

**Comment by filiptrplan** [comment]
> > Also the Request button is still visible after the movie is requested and added. This doesn't happen in `dev` so it should be something in this PR.
> 
> Don't think that's the issue. Issue is that when someone requests the media, it's not added instantaneously into db after backend api call (sometimes it's quick sometimes it's slow). So you need to manually reload to see it

No, it's there even when it is added. So it has the Manage and Delete buttons along with Request.

**Comment by AyushSehrawat** [comment]
> > > Also the Request button is still visible after the movie is requested and added. This doesn't happen in `dev` so it should be something in this PR.
> > 
> > 
> > Don't think that's the issue. Issue is that when someone requests the media, it's not added instantaneously into db after backend api call (sometimes it's quick sometimes it's slow). So you need to manually reload to see it
> 
> No, it's there even when it is added. So it has the Manage and Delete buttons along with Request.

Oh that's weird then. I suspect it's related to backend or maybe using old code to get from data

**Comment by davidemarcoli** [comment]
> Also the Request button is still visible after the movie is requested and added. This doesn't happen in `dev` so it should be something in this PR.

This is fixed with the latest commit

**Pull request merged**
