### PR TITLE
fix: add new states to the frontend

### PR DESCRIPTION
**Pull request by filiptrplan**
As seen in #105 the new states in the backend weren't yet added to the frontend. This fixes the "undefined" show status.

### CODE REVIEW

**Comment by AyushSehrawat** [comment]
Needs to be changed in Library section too

**Review by AyushSehrawat — APPROVED** [review]

**Comment by AyushSehrawat** [comment]
https://github.com/rivenmedia/riven-frontend/blob/main/src/routes/summary/%2Bpage.server.ts

**Review by AyushSehrawat — COMMENTED** [review]
https://github.com/rivenmedia/riven-frontend/blob/main/src/routes/summary/%2Bpage.server.ts

This file requires some changes. I think you import the states type (extend if ts giving issue) and then map in states select

**Comment by AyushSehrawat** [comment]
You can run `pnpm run format` to format and `pnpm run lint`to check

**Comment by filiptrplan** [comment]
> You can run `pnpm run format` to format and `pnpm run lint`to check


The lint is failing because of the following file, this should be fixed in another PR. I will fix the other file as you requested.
```
[warn] .github/workflows/discord-release.yml
```

**Comment by AyushSehrawat** [comment]
> > You can run `pnpm run format` to format and `pnpm run lint`to check
> 
> The lint is failing because of the following file, this should be fixed in another PR. I will fix the other file as you requested.
> 
> ```
> [warn] .github/workflows/discord-release.yml
> ```

You can fix in this pr only :)

**Review by AyushSehrawat — APPROVED** [review]

**Pull request merged**
